#!/usr/bin/python

# factotum - a simple http REST like server for arbitrary commands
# factotum configtool - simple manipulation of the config.yaml
# Copyright (C) 2014 Michael Rice <michael@riceclan.org>
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import rtyaml

# Load YAML file
c=rtyaml.load(file('config.yaml','r'))

# <changes>

c['interface'] = '0.0.0.0'

# </changes>

# Save YAML file
rtyaml.dump(c,file('config.yaml','w'))
